version: "3"
services:

  Nginx:
    restart: always
    container_name: "OMS-Nginx"
    image: nginx:alpine
    # 映射端口
    ports:
      - 90:80
    networks:
      - OMS-Network
    # 数据卷
    volumes:
      - "$PWD/nginx/html:/usr/share/nginx/html"

  MySQL:
    restart: always
    container_name: "OMS-MySQL"
    image: mysql:8
    ports:
      - 33061:3306
    networks:
      - OMS-Network
    volumes:
      - "$PWD/mysql/data:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: OperationsManagementSuiteV3DB
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: rengu
      MYSQL_PASSWORD: rengu

  service:
    restart: always
    container_name: "OMS-Server"
    build:
      context: ./OMS-Server
      dockerfile: Dockerfile
    networks:
      - OMS-Network
    # 依赖项
    depends_on:
      - MySQL
      - Nginx

networks:
  OMS-Network:
    driver: bridge